services:
  db:
    image: postgres:18
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql

  backend:
    depends_on:
      - db
    environment:
      NODE_ENV: development
      PORT: "4000"
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    build:
      context: .
      dockerfile: ./devops/docker/Dockerfile.backend
      target: dev
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:4000/api/health').then(r=>process.exit(r.ok?0:1)).catch(() => process.exit(1))"]
      interval: 5s
      timeout: 3s
      retries: 20

  frontend:
    environment:
      NODE_ENV: development
      API_PROXY_TARGET: "http://backend:4000"
      VITE_BACKEND_SERVER: ${VITE_BACKEND_SERVER}
    build:
      context: .
      dockerfile: ./devops/docker/Dockerfile.frontend
      target: dev
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000 > /dev/null"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata:
